import json
import os
import sys
import uuid
from datetime import datetime

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from shared.aws_clients import s3, dynamodb
from shared.jwt_helper import verify_token
from shared.photo_access import validate_photo_code
from shared.api_utils import json_response

def handler(event, context):
    try:
        headers = event.get("headers", {})
        auth_header = headers.get("authorization", headers.get("Authorization", ""))
        
        if not auth_header.startswith("Bearer "):
            return json_response(401, {"error": "Non autorizzato"})
            
        token = auth_header.split(" ")[1]
        payload = verify_token(token)
        
        if not payload:
            return json_response(401, {"error": "Token invalido o scaduto"})

        # Autorizzazione upload: admin sempre, altrimenti serve un codice
        # di accesso foto valido (header X-Photo-Code, dal link speciale).
        is_admin = bool(payload.get("isAdmin", False))
        photo_code = headers.get("x-photo-code", headers.get("X-Photo-Code", ""))
        if not is_admin and not validate_photo_code(photo_code):
            return json_response(403, {"error": "Caricamento foto non abilitato"})

        user_name = payload.get("name", "Ospite").replace(" ", "")
        
        body = json.loads(event.get("body", "{}"))
        filename = body.get("filename", "")
        content_type = body.get("contentType", "image/jpeg")
        
        if not filename:
            return json_response(400, {"error": "Filename mancante"})
        
        # Generate identifier and unique key
        photo_id = str(uuid.uuid4())
        short_id = photo_id[:8]
        ext = filename.split(".")[-1] if "." in filename else "jpg"
        s3_key = f"uploads/{user_name}-{short_id}.{ext}"
        
        bucket_name = "wedding-photos-local" if os.getenv("ENV", "local") == "local" else os.getenv("S3_BUCKET", "wedding-photos-prod")
        
        # Generate presigned URL
        presigned_url = s3.generate_presigned_url(
            'put_object',
            Params={
                'Bucket': bucket_name,
                'Key': s3_key,
                'ContentType': content_type
            },
            ExpiresIn=3600 # 1 hour
        )
        
        # In local dev, fix the URL if needed so browser can reach it
        if os.getenv("ENV", "local") == "local":
            presigned_url = presigned_url.replace("http://minio:9000", "http://localhost:9000")
        
        # Save placeholder in DB
        table = dynamodb.Table("WeddingPhotos")
        table.put_item(
            Item={
                "PK": f"PHOTO#{photo_id}",
                "uploadedBy": payload.get("phone"),
                "uploaderName": payload.get("name", "Ospite"),
                "s3Key": s3_key,
                "uploadedAt": datetime.utcnow().isoformat(),
                "approved": False,
                "type": "PHOTO"
            }
        )
        
        # If running locally, we need to adjust the MinIO URL if nextjs is calling from browser
        # but for simplicity we return the presigned url generated by boto3 (it will use http://localhost:9000 if configured properly)
        
        return json_response(200, {
            "uploadUrl": presigned_url,
            "key": s3_key
        })
        
    except Exception as e:
        print(f"Errore: {e}")
        return json_response(500, {"error": "Errore interno server"})
